#server.port=8761
#spring.application.name=first-cloud-server
#spring.profiles.active= slave1
#eureka.instance.hostname=slave1
#eureka.client.service-url.defaultZone = http://slave2:8762/eureka/
#---
server:
  port: 8761
spring:
  application:
    name: first-cloud-server
  profiles: slave1
eureka:
  instance:
    hostname: slavel
  client:
    service-url:
      defaultZone: http://slave2:8762/eureka/,http://slave3:8763/eureka/
---
server:
  port: 8762
spring:
  application:
    name: first-cloud-server
  profiles: slave2
eureka:
  instance:
    hostname: slave2
  client:
    service-url:
      defaultZone: http://slave1:8761/eureka/,http://slave3:8763/eureka/
---
server:
  port: 8763
spring:
  application:
    name: first-cloud-server
  profiles: slave3
eureka:
  instance:
    hostname: slave3
  client:
    service-url:
      defaultZone: http://slave1:8761/eureka/,http://slave2:8762/eureka/